### ISSUE TITLE
Todo List

### ISSUE THREAD

**Issue by IanCaunce** [IanCaunce/react-hello-world#2]
- [ ] Checkbox to mark as done
 - [x] List of things #3 
- [ ] Re-order (nice to have)
 - [ ] Remove from list
 - [x] Edit item
